### ISSUE TITLE
Im Eddie 

### ISSUE THREAD

**Issue by AR752003** [Web-Dev-Crew/support#3]
Let me join in

**Comment by MhL5** [comment]
you've been invited to join the Web Dev Crew! 🎉
An invitation email is on its way to your inbox, but you can also accept the invitation right away by heading over to [GitHub](https://github.com/Web-Dev-Crew).
We're excited to have you on board!

**Comment by sameed02** [comment]
join

**Comment by MhL5** [comment]
> join

you've been invited to join the Web Dev Crew! 🎉
An invitation email is on its way to your inbox, but you can also accept the invitation right away by heading over to [GitHub](https://github.com/Web-Dev-Crew).
We're excited to have you on board!
